#!/bin/sh
#  Extracts bytes from stdin and write to stdout
#  Example: 
#       echo "This is a test" | ./extract-bytes 1 6
#  Outputs
#       his is

if [ $# -ne 2 ]; then
   echo "usage: extract-bytes <offset> <length>"
   exit 1
fi

OFFSET=$1
LENGTH=$2

dd bs=1 count=$LENGTH iseek=$OFFSET 2>/dev/null
